filledcurves with above/below threshold and fillcolor implemented.
PDLPorters/PDL-Graphics-Gnuplot pull request #105
Opened 2024-11-15 18:23 UTC by vikasnkumar

example added as well. tested and it works.

2024-11-16 02:20 UTC, mohawk2 requested changes

2024-11-16 02:20 UTC, mohawk2 commented on examples/demo.pl
> +
Can you drop this blank line? Thanks.

2024-11-16 02:20 UTC, mohawk2 commented on lib/PDL/Graphics/Gnuplot.pm
> +	fc => ["fillcolor"]
Can you please add a `,` on the end, so one could add another line here without spurious diffs, given Perl allows that?

2024-11-21 17:14 UTC, vikasnkumar commented
@mohawk2 any updates here ? is this ready for release ?

2024-11-21 17:30 UTC, mohawk2 approved these changes

2024-11-21 17:35 UTC, merged

2024-11-21 17:40 UTC, mohawk2 commented
Thanks! Just released as 2.032.